export const routes = [
  "/",
  "/about",
  "/aiims-nursing-officer-recruitment",
  "/blog",
  "/contact",
  "/courses",
  "/norcet-admit-card",
  "/norcet-age-limit",
  "/norcet-application-form",
  "/norcet-application-process",
  "/norcet-eligibility",
  "/norcet-exam-date",
  "/norcet-exam-pattern",
  "/norcet-full-form",
  "/norcet-notification",
  "/norcet-selection-process",
  "/norcet-syllabus",
  "/norcet-vacancy",
  "/what-is-norcet",
  "/previous-year-papers",
  "/privacy-policy",
  "/terms"
] as const;
